/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the PersonDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PersonDetails{}

// PersonDetails struct for PersonDetails
type PersonDetails struct {
	Id *float32 `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
	Birthday NullableString `json:"birthday,omitempty"`
	Deathday NullableString `json:"deathday,omitempty"`
	KnownForDepartment *string `json:"knownForDepartment,omitempty"`
	AlsoKnownAs []string `json:"alsoKnownAs,omitempty"`
	Gender *float32 `json:"gender,omitempty"`
	Biography *string `json:"biography,omitempty"`
	Popularity *float32 `json:"popularity,omitempty"`
	PlaceOfBirth NullableString `json:"placeOfBirth,omitempty"`
	ProfilePath NullableString `json:"profilePath,omitempty"`
	Adult *bool `json:"adult,omitempty"`
	ImdbId NullableString `json:"imdbId,omitempty"`
	Homepage NullableString `json:"homepage,omitempty"`
}

// NewPersonDetails instantiates a new PersonDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPersonDetails() *PersonDetails {
	this := PersonDetails{}
	return &this
}

// NewPersonDetailsWithDefaults instantiates a new PersonDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPersonDetailsWithDefaults() *PersonDetails {
	this := PersonDetails{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PersonDetails) GetId() float32 {
	if o == nil || IsNil(o.Id) {
		var ret float32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonDetails) GetIdOk() (*float32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PersonDetails) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given float32 and assigns it to the Id field.
func (o *PersonDetails) SetId(v float32) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PersonDetails) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonDetails) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PersonDetails) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PersonDetails) SetName(v string) {
	o.Name = &v
}

// GetBirthday returns the Birthday field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PersonDetails) GetBirthday() string {
	if o == nil || IsNil(o.Birthday.Get()) {
		var ret string
		return ret
	}
	return *o.Birthday.Get()
}

// GetBirthdayOk returns a tuple with the Birthday field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PersonDetails) GetBirthdayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Birthday.Get(), o.Birthday.IsSet()
}

// HasBirthday returns a boolean if a field has been set.
func (o *PersonDetails) HasBirthday() bool {
	if o != nil && o.Birthday.IsSet() {
		return true
	}

	return false
}

// SetBirthday gets a reference to the given NullableString and assigns it to the Birthday field.
func (o *PersonDetails) SetBirthday(v string) {
	o.Birthday.Set(&v)
}
// SetBirthdayNil sets the value for Birthday to be an explicit nil
func (o *PersonDetails) SetBirthdayNil() {
	o.Birthday.Set(nil)
}

// UnsetBirthday ensures that no value is present for Birthday, not even an explicit nil
func (o *PersonDetails) UnsetBirthday() {
	o.Birthday.Unset()
}

// GetDeathday returns the Deathday field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PersonDetails) GetDeathday() string {
	if o == nil || IsNil(o.Deathday.Get()) {
		var ret string
		return ret
	}
	return *o.Deathday.Get()
}

// GetDeathdayOk returns a tuple with the Deathday field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PersonDetails) GetDeathdayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Deathday.Get(), o.Deathday.IsSet()
}

// HasDeathday returns a boolean if a field has been set.
func (o *PersonDetails) HasDeathday() bool {
	if o != nil && o.Deathday.IsSet() {
		return true
	}

	return false
}

// SetDeathday gets a reference to the given NullableString and assigns it to the Deathday field.
func (o *PersonDetails) SetDeathday(v string) {
	o.Deathday.Set(&v)
}
// SetDeathdayNil sets the value for Deathday to be an explicit nil
func (o *PersonDetails) SetDeathdayNil() {
	o.Deathday.Set(nil)
}

// UnsetDeathday ensures that no value is present for Deathday, not even an explicit nil
func (o *PersonDetails) UnsetDeathday() {
	o.Deathday.Unset()
}

// GetKnownForDepartment returns the KnownForDepartment field value if set, zero value otherwise.
func (o *PersonDetails) GetKnownForDepartment() string {
	if o == nil || IsNil(o.KnownForDepartment) {
		var ret string
		return ret
	}
	return *o.KnownForDepartment
}

// GetKnownForDepartmentOk returns a tuple with the KnownForDepartment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonDetails) GetKnownForDepartmentOk() (*string, bool) {
	if o == nil || IsNil(o.KnownForDepartment) {
		return nil, false
	}
	return o.KnownForDepartment, true
}

// HasKnownForDepartment returns a boolean if a field has been set.
func (o *PersonDetails) HasKnownForDepartment() bool {
	if o != nil && !IsNil(o.KnownForDepartment) {
		return true
	}

	return false
}

// SetKnownForDepartment gets a reference to the given string and assigns it to the KnownForDepartment field.
func (o *PersonDetails) SetKnownForDepartment(v string) {
	o.KnownForDepartment = &v
}

// GetAlsoKnownAs returns the AlsoKnownAs field value if set, zero value otherwise.
func (o *PersonDetails) GetAlsoKnownAs() []string {
	if o == nil || IsNil(o.AlsoKnownAs) {
		var ret []string
		return ret
	}
	return o.AlsoKnownAs
}

// GetAlsoKnownAsOk returns a tuple with the AlsoKnownAs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonDetails) GetAlsoKnownAsOk() ([]string, bool) {
	if o == nil || IsNil(o.AlsoKnownAs) {
		return nil, false
	}
	return o.AlsoKnownAs, true
}

// HasAlsoKnownAs returns a boolean if a field has been set.
func (o *PersonDetails) HasAlsoKnownAs() bool {
	if o != nil && !IsNil(o.AlsoKnownAs) {
		return true
	}

	return false
}

// SetAlsoKnownAs gets a reference to the given []string and assigns it to the AlsoKnownAs field.
func (o *PersonDetails) SetAlsoKnownAs(v []string) {
	o.AlsoKnownAs = v
}

// GetGender returns the Gender field value if set, zero value otherwise.
func (o *PersonDetails) GetGender() float32 {
	if o == nil || IsNil(o.Gender) {
		var ret float32
		return ret
	}
	return *o.Gender
}

// GetGenderOk returns a tuple with the Gender field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonDetails) GetGenderOk() (*float32, bool) {
	if o == nil || IsNil(o.Gender) {
		return nil, false
	}
	return o.Gender, true
}

// HasGender returns a boolean if a field has been set.
func (o *PersonDetails) HasGender() bool {
	if o != nil && !IsNil(o.Gender) {
		return true
	}

	return false
}

// SetGender gets a reference to the given float32 and assigns it to the Gender field.
func (o *PersonDetails) SetGender(v float32) {
	o.Gender = &v
}

// GetBiography returns the Biography field value if set, zero value otherwise.
func (o *PersonDetails) GetBiography() string {
	if o == nil || IsNil(o.Biography) {
		var ret string
		return ret
	}
	return *o.Biography
}

// GetBiographyOk returns a tuple with the Biography field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonDetails) GetBiographyOk() (*string, bool) {
	if o == nil || IsNil(o.Biography) {
		return nil, false
	}
	return o.Biography, true
}

// HasBiography returns a boolean if a field has been set.
func (o *PersonDetails) HasBiography() bool {
	if o != nil && !IsNil(o.Biography) {
		return true
	}

	return false
}

// SetBiography gets a reference to the given string and assigns it to the Biography field.
func (o *PersonDetails) SetBiography(v string) {
	o.Biography = &v
}

// GetPopularity returns the Popularity field value if set, zero value otherwise.
func (o *PersonDetails) GetPopularity() float32 {
	if o == nil || IsNil(o.Popularity) {
		var ret float32
		return ret
	}
	return *o.Popularity
}

// GetPopularityOk returns a tuple with the Popularity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonDetails) GetPopularityOk() (*float32, bool) {
	if o == nil || IsNil(o.Popularity) {
		return nil, false
	}
	return o.Popularity, true
}

// HasPopularity returns a boolean if a field has been set.
func (o *PersonDetails) HasPopularity() bool {
	if o != nil && !IsNil(o.Popularity) {
		return true
	}

	return false
}

// SetPopularity gets a reference to the given float32 and assigns it to the Popularity field.
func (o *PersonDetails) SetPopularity(v float32) {
	o.Popularity = &v
}

// GetPlaceOfBirth returns the PlaceOfBirth field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PersonDetails) GetPlaceOfBirth() string {
	if o == nil || IsNil(o.PlaceOfBirth.Get()) {
		var ret string
		return ret
	}
	return *o.PlaceOfBirth.Get()
}

// GetPlaceOfBirthOk returns a tuple with the PlaceOfBirth field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PersonDetails) GetPlaceOfBirthOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PlaceOfBirth.Get(), o.PlaceOfBirth.IsSet()
}

// HasPlaceOfBirth returns a boolean if a field has been set.
func (o *PersonDetails) HasPlaceOfBirth() bool {
	if o != nil && o.PlaceOfBirth.IsSet() {
		return true
	}

	return false
}

// SetPlaceOfBirth gets a reference to the given NullableString and assigns it to the PlaceOfBirth field.
func (o *PersonDetails) SetPlaceOfBirth(v string) {
	o.PlaceOfBirth.Set(&v)
}
// SetPlaceOfBirthNil sets the value for PlaceOfBirth to be an explicit nil
func (o *PersonDetails) SetPlaceOfBirthNil() {
	o.PlaceOfBirth.Set(nil)
}

// UnsetPlaceOfBirth ensures that no value is present for PlaceOfBirth, not even an explicit nil
func (o *PersonDetails) UnsetPlaceOfBirth() {
	o.PlaceOfBirth.Unset()
}

// GetProfilePath returns the ProfilePath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PersonDetails) GetProfilePath() string {
	if o == nil || IsNil(o.ProfilePath.Get()) {
		var ret string
		return ret
	}
	return *o.ProfilePath.Get()
}

// GetProfilePathOk returns a tuple with the ProfilePath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PersonDetails) GetProfilePathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProfilePath.Get(), o.ProfilePath.IsSet()
}

// HasProfilePath returns a boolean if a field has been set.
func (o *PersonDetails) HasProfilePath() bool {
	if o != nil && o.ProfilePath.IsSet() {
		return true
	}

	return false
}

// SetProfilePath gets a reference to the given NullableString and assigns it to the ProfilePath field.
func (o *PersonDetails) SetProfilePath(v string) {
	o.ProfilePath.Set(&v)
}
// SetProfilePathNil sets the value for ProfilePath to be an explicit nil
func (o *PersonDetails) SetProfilePathNil() {
	o.ProfilePath.Set(nil)
}

// UnsetProfilePath ensures that no value is present for ProfilePath, not even an explicit nil
func (o *PersonDetails) UnsetProfilePath() {
	o.ProfilePath.Unset()
}

// GetAdult returns the Adult field value if set, zero value otherwise.
func (o *PersonDetails) GetAdult() bool {
	if o == nil || IsNil(o.Adult) {
		var ret bool
		return ret
	}
	return *o.Adult
}

// GetAdultOk returns a tuple with the Adult field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PersonDetails) GetAdultOk() (*bool, bool) {
	if o == nil || IsNil(o.Adult) {
		return nil, false
	}
	return o.Adult, true
}

// HasAdult returns a boolean if a field has been set.
func (o *PersonDetails) HasAdult() bool {
	if o != nil && !IsNil(o.Adult) {
		return true
	}

	return false
}

// SetAdult gets a reference to the given bool and assigns it to the Adult field.
func (o *PersonDetails) SetAdult(v bool) {
	o.Adult = &v
}

// GetImdbId returns the ImdbId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PersonDetails) GetImdbId() string {
	if o == nil || IsNil(o.ImdbId.Get()) {
		var ret string
		return ret
	}
	return *o.ImdbId.Get()
}

// GetImdbIdOk returns a tuple with the ImdbId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PersonDetails) GetImdbIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ImdbId.Get(), o.ImdbId.IsSet()
}

// HasImdbId returns a boolean if a field has been set.
func (o *PersonDetails) HasImdbId() bool {
	if o != nil && o.ImdbId.IsSet() {
		return true
	}

	return false
}

// SetImdbId gets a reference to the given NullableString and assigns it to the ImdbId field.
func (o *PersonDetails) SetImdbId(v string) {
	o.ImdbId.Set(&v)
}
// SetImdbIdNil sets the value for ImdbId to be an explicit nil
func (o *PersonDetails) SetImdbIdNil() {
	o.ImdbId.Set(nil)
}

// UnsetImdbId ensures that no value is present for ImdbId, not even an explicit nil
func (o *PersonDetails) UnsetImdbId() {
	o.ImdbId.Unset()
}

// GetHomepage returns the Homepage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PersonDetails) GetHomepage() string {
	if o == nil || IsNil(o.Homepage.Get()) {
		var ret string
		return ret
	}
	return *o.Homepage.Get()
}

// GetHomepageOk returns a tuple with the Homepage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PersonDetails) GetHomepageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Homepage.Get(), o.Homepage.IsSet()
}

// HasHomepage returns a boolean if a field has been set.
func (o *PersonDetails) HasHomepage() bool {
	if o != nil && o.Homepage.IsSet() {
		return true
	}

	return false
}

// SetHomepage gets a reference to the given NullableString and assigns it to the Homepage field.
func (o *PersonDetails) SetHomepage(v string) {
	o.Homepage.Set(&v)
}
// SetHomepageNil sets the value for Homepage to be an explicit nil
func (o *PersonDetails) SetHomepageNil() {
	o.Homepage.Set(nil)
}

// UnsetHomepage ensures that no value is present for Homepage, not even an explicit nil
func (o *PersonDetails) UnsetHomepage() {
	o.Homepage.Unset()
}

func (o PersonDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PersonDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Birthday.IsSet() {
		toSerialize["birthday"] = o.Birthday.Get()
	}
	if o.Deathday.IsSet() {
		toSerialize["deathday"] = o.Deathday.Get()
	}
	if !IsNil(o.KnownForDepartment) {
		toSerialize["knownForDepartment"] = o.KnownForDepartment
	}
	if !IsNil(o.AlsoKnownAs) {
		toSerialize["alsoKnownAs"] = o.AlsoKnownAs
	}
	if !IsNil(o.Gender) {
		toSerialize["gender"] = o.Gender
	}
	if !IsNil(o.Biography) {
		toSerialize["biography"] = o.Biography
	}
	if !IsNil(o.Popularity) {
		toSerialize["popularity"] = o.Popularity
	}
	if o.PlaceOfBirth.IsSet() {
		toSerialize["placeOfBirth"] = o.PlaceOfBirth.Get()
	}
	if o.ProfilePath.IsSet() {
		toSerialize["profilePath"] = o.ProfilePath.Get()
	}
	if !IsNil(o.Adult) {
		toSerialize["adult"] = o.Adult
	}
	if o.ImdbId.IsSet() {
		toSerialize["imdbId"] = o.ImdbId.Get()
	}
	if o.Homepage.IsSet() {
		toSerialize["homepage"] = o.Homepage.Get()
	}
	return toSerialize, nil
}

type NullablePersonDetails struct {
	value *PersonDetails
	isSet bool
}

func (v NullablePersonDetails) Get() *PersonDetails {
	return v.value
}

func (v *NullablePersonDetails) Set(val *PersonDetails) {
	v.value = val
	v.isSet = true
}

func (v NullablePersonDetails) IsSet() bool {
	return v.isSet
}

func (v *NullablePersonDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePersonDetails(val *PersonDetails) *NullablePersonDetails {
	return &NullablePersonDetails{value: val, isSet: true}
}

func (v NullablePersonDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePersonDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


