/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the User type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &User{}

// User struct for User
type User struct {
	Id int32 `json:"id"`
	Email string `json:"email"`
	Username *string `json:"username,omitempty"`
	PlexUsername *string `json:"plexUsername,omitempty"`
	PlexToken *string `json:"plexToken,omitempty"`
	JellyfinAuthToken *string `json:"jellyfinAuthToken,omitempty"`
	UserType *int32 `json:"userType,omitempty"`
	Permissions *float32 `json:"permissions,omitempty"`
	Avatar *string `json:"avatar,omitempty"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
	Settings *UserSettings `json:"settings,omitempty"`
	RequestCount *float32 `json:"requestCount,omitempty"`
	DisplayName *string `json:"displayName,omitempty"`
	JellyfinUsername NullableString `json:"jellyfinUsername,omitempty"`
	JellyfinUserId NullableString `json:"jellyfinUserId,omitempty"`
	PlexId NullableInt32 `json:"plexId,omitempty"`
	Warnings []string `json:"warnings,omitempty"`
	RecoveryLinkExpirationDate NullableString `json:"recoveryLinkExpirationDate,omitempty"`
	AvatarETag NullableString `json:"avatarETag,omitempty"`
	AvatarVersion NullableInt32 `json:"avatarVersion,omitempty"`
	MovieQuotaLimit NullableFloat32 `json:"movieQuotaLimit,omitempty"`
	MovieQuotaDays NullableFloat32 `json:"movieQuotaDays,omitempty"`
	TvQuotaLimit NullableFloat32 `json:"tvQuotaLimit,omitempty"`
	TvQuotaDays NullableFloat32 `json:"tvQuotaDays,omitempty"`
}

type _User User

// NewUser instantiates a new User object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUser(id int32, email string, createdAt string, updatedAt string) *User {
	this := User{}
	this.Id = id
	this.Email = email
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewUserWithDefaults instantiates a new User object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserWithDefaults() *User {
	this := User{}
	return &this
}

// GetId returns the Id field value
func (o *User) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *User) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *User) SetId(v int32) {
	o.Id = v
}

// GetEmail returns the Email field value
func (o *User) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *User) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *User) SetEmail(v string) {
	o.Email = v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *User) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *User) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *User) SetUsername(v string) {
	o.Username = &v
}

// GetPlexUsername returns the PlexUsername field value if set, zero value otherwise.
func (o *User) GetPlexUsername() string {
	if o == nil || IsNil(o.PlexUsername) {
		var ret string
		return ret
	}
	return *o.PlexUsername
}

// GetPlexUsernameOk returns a tuple with the PlexUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetPlexUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.PlexUsername) {
		return nil, false
	}
	return o.PlexUsername, true
}

// HasPlexUsername returns a boolean if a field has been set.
func (o *User) HasPlexUsername() bool {
	if o != nil && !IsNil(o.PlexUsername) {
		return true
	}

	return false
}

// SetPlexUsername gets a reference to the given string and assigns it to the PlexUsername field.
func (o *User) SetPlexUsername(v string) {
	o.PlexUsername = &v
}

// GetPlexToken returns the PlexToken field value if set, zero value otherwise.
func (o *User) GetPlexToken() string {
	if o == nil || IsNil(o.PlexToken) {
		var ret string
		return ret
	}
	return *o.PlexToken
}

// GetPlexTokenOk returns a tuple with the PlexToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetPlexTokenOk() (*string, bool) {
	if o == nil || IsNil(o.PlexToken) {
		return nil, false
	}
	return o.PlexToken, true
}

// HasPlexToken returns a boolean if a field has been set.
func (o *User) HasPlexToken() bool {
	if o != nil && !IsNil(o.PlexToken) {
		return true
	}

	return false
}

// SetPlexToken gets a reference to the given string and assigns it to the PlexToken field.
func (o *User) SetPlexToken(v string) {
	o.PlexToken = &v
}

// GetJellyfinAuthToken returns the JellyfinAuthToken field value if set, zero value otherwise.
func (o *User) GetJellyfinAuthToken() string {
	if o == nil || IsNil(o.JellyfinAuthToken) {
		var ret string
		return ret
	}
	return *o.JellyfinAuthToken
}

// GetJellyfinAuthTokenOk returns a tuple with the JellyfinAuthToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetJellyfinAuthTokenOk() (*string, bool) {
	if o == nil || IsNil(o.JellyfinAuthToken) {
		return nil, false
	}
	return o.JellyfinAuthToken, true
}

// HasJellyfinAuthToken returns a boolean if a field has been set.
func (o *User) HasJellyfinAuthToken() bool {
	if o != nil && !IsNil(o.JellyfinAuthToken) {
		return true
	}

	return false
}

// SetJellyfinAuthToken gets a reference to the given string and assigns it to the JellyfinAuthToken field.
func (o *User) SetJellyfinAuthToken(v string) {
	o.JellyfinAuthToken = &v
}

// GetUserType returns the UserType field value if set, zero value otherwise.
func (o *User) GetUserType() int32 {
	if o == nil || IsNil(o.UserType) {
		var ret int32
		return ret
	}
	return *o.UserType
}

// GetUserTypeOk returns a tuple with the UserType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetUserTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.UserType) {
		return nil, false
	}
	return o.UserType, true
}

// HasUserType returns a boolean if a field has been set.
func (o *User) HasUserType() bool {
	if o != nil && !IsNil(o.UserType) {
		return true
	}

	return false
}

// SetUserType gets a reference to the given int32 and assigns it to the UserType field.
func (o *User) SetUserType(v int32) {
	o.UserType = &v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *User) GetPermissions() float32 {
	if o == nil || IsNil(o.Permissions) {
		var ret float32
		return ret
	}
	return *o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetPermissionsOk() (*float32, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *User) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given float32 and assigns it to the Permissions field.
func (o *User) SetPermissions(v float32) {
	o.Permissions = &v
}

// GetAvatar returns the Avatar field value if set, zero value otherwise.
func (o *User) GetAvatar() string {
	if o == nil || IsNil(o.Avatar) {
		var ret string
		return ret
	}
	return *o.Avatar
}

// GetAvatarOk returns a tuple with the Avatar field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetAvatarOk() (*string, bool) {
	if o == nil || IsNil(o.Avatar) {
		return nil, false
	}
	return o.Avatar, true
}

// HasAvatar returns a boolean if a field has been set.
func (o *User) HasAvatar() bool {
	if o != nil && !IsNil(o.Avatar) {
		return true
	}

	return false
}

// SetAvatar gets a reference to the given string and assigns it to the Avatar field.
func (o *User) SetAvatar(v string) {
	o.Avatar = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *User) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *User) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *User) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *User) GetUpdatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *User) GetUpdatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *User) SetUpdatedAt(v string) {
	o.UpdatedAt = v
}

// GetSettings returns the Settings field value if set, zero value otherwise.
func (o *User) GetSettings() UserSettings {
	if o == nil || IsNil(o.Settings) {
		var ret UserSettings
		return ret
	}
	return *o.Settings
}

// GetSettingsOk returns a tuple with the Settings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetSettingsOk() (*UserSettings, bool) {
	if o == nil || IsNil(o.Settings) {
		return nil, false
	}
	return o.Settings, true
}

// HasSettings returns a boolean if a field has been set.
func (o *User) HasSettings() bool {
	if o != nil && !IsNil(o.Settings) {
		return true
	}

	return false
}

// SetSettings gets a reference to the given UserSettings and assigns it to the Settings field.
func (o *User) SetSettings(v UserSettings) {
	o.Settings = &v
}

// GetRequestCount returns the RequestCount field value if set, zero value otherwise.
func (o *User) GetRequestCount() float32 {
	if o == nil || IsNil(o.RequestCount) {
		var ret float32
		return ret
	}
	return *o.RequestCount
}

// GetRequestCountOk returns a tuple with the RequestCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetRequestCountOk() (*float32, bool) {
	if o == nil || IsNil(o.RequestCount) {
		return nil, false
	}
	return o.RequestCount, true
}

// HasRequestCount returns a boolean if a field has been set.
func (o *User) HasRequestCount() bool {
	if o != nil && !IsNil(o.RequestCount) {
		return true
	}

	return false
}

// SetRequestCount gets a reference to the given float32 and assigns it to the RequestCount field.
func (o *User) SetRequestCount(v float32) {
	o.RequestCount = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *User) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *User) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *User) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetJellyfinUsername returns the JellyfinUsername field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetJellyfinUsername() string {
	if o == nil || IsNil(o.JellyfinUsername.Get()) {
		var ret string
		return ret
	}
	return *o.JellyfinUsername.Get()
}

// GetJellyfinUsernameOk returns a tuple with the JellyfinUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetJellyfinUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.JellyfinUsername.Get(), o.JellyfinUsername.IsSet()
}

// HasJellyfinUsername returns a boolean if a field has been set.
func (o *User) HasJellyfinUsername() bool {
	if o != nil && o.JellyfinUsername.IsSet() {
		return true
	}

	return false
}

// SetJellyfinUsername gets a reference to the given NullableString and assigns it to the JellyfinUsername field.
func (o *User) SetJellyfinUsername(v string) {
	o.JellyfinUsername.Set(&v)
}
// SetJellyfinUsernameNil sets the value for JellyfinUsername to be an explicit nil
func (o *User) SetJellyfinUsernameNil() {
	o.JellyfinUsername.Set(nil)
}

// UnsetJellyfinUsername ensures that no value is present for JellyfinUsername, not even an explicit nil
func (o *User) UnsetJellyfinUsername() {
	o.JellyfinUsername.Unset()
}

// GetJellyfinUserId returns the JellyfinUserId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetJellyfinUserId() string {
	if o == nil || IsNil(o.JellyfinUserId.Get()) {
		var ret string
		return ret
	}
	return *o.JellyfinUserId.Get()
}

// GetJellyfinUserIdOk returns a tuple with the JellyfinUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetJellyfinUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.JellyfinUserId.Get(), o.JellyfinUserId.IsSet()
}

// HasJellyfinUserId returns a boolean if a field has been set.
func (o *User) HasJellyfinUserId() bool {
	if o != nil && o.JellyfinUserId.IsSet() {
		return true
	}

	return false
}

// SetJellyfinUserId gets a reference to the given NullableString and assigns it to the JellyfinUserId field.
func (o *User) SetJellyfinUserId(v string) {
	o.JellyfinUserId.Set(&v)
}
// SetJellyfinUserIdNil sets the value for JellyfinUserId to be an explicit nil
func (o *User) SetJellyfinUserIdNil() {
	o.JellyfinUserId.Set(nil)
}

// UnsetJellyfinUserId ensures that no value is present for JellyfinUserId, not even an explicit nil
func (o *User) UnsetJellyfinUserId() {
	o.JellyfinUserId.Unset()
}

// GetPlexId returns the PlexId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetPlexId() int32 {
	if o == nil || IsNil(o.PlexId.Get()) {
		var ret int32
		return ret
	}
	return *o.PlexId.Get()
}

// GetPlexIdOk returns a tuple with the PlexId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetPlexIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.PlexId.Get(), o.PlexId.IsSet()
}

// HasPlexId returns a boolean if a field has been set.
func (o *User) HasPlexId() bool {
	if o != nil && o.PlexId.IsSet() {
		return true
	}

	return false
}

// SetPlexId gets a reference to the given NullableInt32 and assigns it to the PlexId field.
func (o *User) SetPlexId(v int32) {
	o.PlexId.Set(&v)
}
// SetPlexIdNil sets the value for PlexId to be an explicit nil
func (o *User) SetPlexIdNil() {
	o.PlexId.Set(nil)
}

// UnsetPlexId ensures that no value is present for PlexId, not even an explicit nil
func (o *User) UnsetPlexId() {
	o.PlexId.Unset()
}

// GetWarnings returns the Warnings field value if set, zero value otherwise.
func (o *User) GetWarnings() []string {
	if o == nil || IsNil(o.Warnings) {
		var ret []string
		return ret
	}
	return o.Warnings
}

// GetWarningsOk returns a tuple with the Warnings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *User) GetWarningsOk() ([]string, bool) {
	if o == nil || IsNil(o.Warnings) {
		return nil, false
	}
	return o.Warnings, true
}

// HasWarnings returns a boolean if a field has been set.
func (o *User) HasWarnings() bool {
	if o != nil && !IsNil(o.Warnings) {
		return true
	}

	return false
}

// SetWarnings gets a reference to the given []string and assigns it to the Warnings field.
func (o *User) SetWarnings(v []string) {
	o.Warnings = v
}

// GetRecoveryLinkExpirationDate returns the RecoveryLinkExpirationDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetRecoveryLinkExpirationDate() string {
	if o == nil || IsNil(o.RecoveryLinkExpirationDate.Get()) {
		var ret string
		return ret
	}
	return *o.RecoveryLinkExpirationDate.Get()
}

// GetRecoveryLinkExpirationDateOk returns a tuple with the RecoveryLinkExpirationDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetRecoveryLinkExpirationDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RecoveryLinkExpirationDate.Get(), o.RecoveryLinkExpirationDate.IsSet()
}

// HasRecoveryLinkExpirationDate returns a boolean if a field has been set.
func (o *User) HasRecoveryLinkExpirationDate() bool {
	if o != nil && o.RecoveryLinkExpirationDate.IsSet() {
		return true
	}

	return false
}

// SetRecoveryLinkExpirationDate gets a reference to the given NullableString and assigns it to the RecoveryLinkExpirationDate field.
func (o *User) SetRecoveryLinkExpirationDate(v string) {
	o.RecoveryLinkExpirationDate.Set(&v)
}
// SetRecoveryLinkExpirationDateNil sets the value for RecoveryLinkExpirationDate to be an explicit nil
func (o *User) SetRecoveryLinkExpirationDateNil() {
	o.RecoveryLinkExpirationDate.Set(nil)
}

// UnsetRecoveryLinkExpirationDate ensures that no value is present for RecoveryLinkExpirationDate, not even an explicit nil
func (o *User) UnsetRecoveryLinkExpirationDate() {
	o.RecoveryLinkExpirationDate.Unset()
}

// GetAvatarETag returns the AvatarETag field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetAvatarETag() string {
	if o == nil || IsNil(o.AvatarETag.Get()) {
		var ret string
		return ret
	}
	return *o.AvatarETag.Get()
}

// GetAvatarETagOk returns a tuple with the AvatarETag field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetAvatarETagOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AvatarETag.Get(), o.AvatarETag.IsSet()
}

// HasAvatarETag returns a boolean if a field has been set.
func (o *User) HasAvatarETag() bool {
	if o != nil && o.AvatarETag.IsSet() {
		return true
	}

	return false
}

// SetAvatarETag gets a reference to the given NullableString and assigns it to the AvatarETag field.
func (o *User) SetAvatarETag(v string) {
	o.AvatarETag.Set(&v)
}
// SetAvatarETagNil sets the value for AvatarETag to be an explicit nil
func (o *User) SetAvatarETagNil() {
	o.AvatarETag.Set(nil)
}

// UnsetAvatarETag ensures that no value is present for AvatarETag, not even an explicit nil
func (o *User) UnsetAvatarETag() {
	o.AvatarETag.Unset()
}

// GetAvatarVersion returns the AvatarVersion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetAvatarVersion() int32 {
	if o == nil || IsNil(o.AvatarVersion.Get()) {
		var ret int32
		return ret
	}
	return *o.AvatarVersion.Get()
}

// GetAvatarVersionOk returns a tuple with the AvatarVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetAvatarVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.AvatarVersion.Get(), o.AvatarVersion.IsSet()
}

// HasAvatarVersion returns a boolean if a field has been set.
func (o *User) HasAvatarVersion() bool {
	if o != nil && o.AvatarVersion.IsSet() {
		return true
	}

	return false
}

// SetAvatarVersion gets a reference to the given NullableInt32 and assigns it to the AvatarVersion field.
func (o *User) SetAvatarVersion(v int32) {
	o.AvatarVersion.Set(&v)
}
// SetAvatarVersionNil sets the value for AvatarVersion to be an explicit nil
func (o *User) SetAvatarVersionNil() {
	o.AvatarVersion.Set(nil)
}

// UnsetAvatarVersion ensures that no value is present for AvatarVersion, not even an explicit nil
func (o *User) UnsetAvatarVersion() {
	o.AvatarVersion.Unset()
}

// GetMovieQuotaLimit returns the MovieQuotaLimit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetMovieQuotaLimit() float32 {
	if o == nil || IsNil(o.MovieQuotaLimit.Get()) {
		var ret float32
		return ret
	}
	return *o.MovieQuotaLimit.Get()
}

// GetMovieQuotaLimitOk returns a tuple with the MovieQuotaLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetMovieQuotaLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MovieQuotaLimit.Get(), o.MovieQuotaLimit.IsSet()
}

// HasMovieQuotaLimit returns a boolean if a field has been set.
func (o *User) HasMovieQuotaLimit() bool {
	if o != nil && o.MovieQuotaLimit.IsSet() {
		return true
	}

	return false
}

// SetMovieQuotaLimit gets a reference to the given NullableFloat32 and assigns it to the MovieQuotaLimit field.
func (o *User) SetMovieQuotaLimit(v float32) {
	o.MovieQuotaLimit.Set(&v)
}
// SetMovieQuotaLimitNil sets the value for MovieQuotaLimit to be an explicit nil
func (o *User) SetMovieQuotaLimitNil() {
	o.MovieQuotaLimit.Set(nil)
}

// UnsetMovieQuotaLimit ensures that no value is present for MovieQuotaLimit, not even an explicit nil
func (o *User) UnsetMovieQuotaLimit() {
	o.MovieQuotaLimit.Unset()
}

// GetMovieQuotaDays returns the MovieQuotaDays field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetMovieQuotaDays() float32 {
	if o == nil || IsNil(o.MovieQuotaDays.Get()) {
		var ret float32
		return ret
	}
	return *o.MovieQuotaDays.Get()
}

// GetMovieQuotaDaysOk returns a tuple with the MovieQuotaDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetMovieQuotaDaysOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MovieQuotaDays.Get(), o.MovieQuotaDays.IsSet()
}

// HasMovieQuotaDays returns a boolean if a field has been set.
func (o *User) HasMovieQuotaDays() bool {
	if o != nil && o.MovieQuotaDays.IsSet() {
		return true
	}

	return false
}

// SetMovieQuotaDays gets a reference to the given NullableFloat32 and assigns it to the MovieQuotaDays field.
func (o *User) SetMovieQuotaDays(v float32) {
	o.MovieQuotaDays.Set(&v)
}
// SetMovieQuotaDaysNil sets the value for MovieQuotaDays to be an explicit nil
func (o *User) SetMovieQuotaDaysNil() {
	o.MovieQuotaDays.Set(nil)
}

// UnsetMovieQuotaDays ensures that no value is present for MovieQuotaDays, not even an explicit nil
func (o *User) UnsetMovieQuotaDays() {
	o.MovieQuotaDays.Unset()
}

// GetTvQuotaLimit returns the TvQuotaLimit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetTvQuotaLimit() float32 {
	if o == nil || IsNil(o.TvQuotaLimit.Get()) {
		var ret float32
		return ret
	}
	return *o.TvQuotaLimit.Get()
}

// GetTvQuotaLimitOk returns a tuple with the TvQuotaLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetTvQuotaLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TvQuotaLimit.Get(), o.TvQuotaLimit.IsSet()
}

// HasTvQuotaLimit returns a boolean if a field has been set.
func (o *User) HasTvQuotaLimit() bool {
	if o != nil && o.TvQuotaLimit.IsSet() {
		return true
	}

	return false
}

// SetTvQuotaLimit gets a reference to the given NullableFloat32 and assigns it to the TvQuotaLimit field.
func (o *User) SetTvQuotaLimit(v float32) {
	o.TvQuotaLimit.Set(&v)
}
// SetTvQuotaLimitNil sets the value for TvQuotaLimit to be an explicit nil
func (o *User) SetTvQuotaLimitNil() {
	o.TvQuotaLimit.Set(nil)
}

// UnsetTvQuotaLimit ensures that no value is present for TvQuotaLimit, not even an explicit nil
func (o *User) UnsetTvQuotaLimit() {
	o.TvQuotaLimit.Unset()
}

// GetTvQuotaDays returns the TvQuotaDays field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *User) GetTvQuotaDays() float32 {
	if o == nil || IsNil(o.TvQuotaDays.Get()) {
		var ret float32
		return ret
	}
	return *o.TvQuotaDays.Get()
}

// GetTvQuotaDaysOk returns a tuple with the TvQuotaDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *User) GetTvQuotaDaysOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TvQuotaDays.Get(), o.TvQuotaDays.IsSet()
}

// HasTvQuotaDays returns a boolean if a field has been set.
func (o *User) HasTvQuotaDays() bool {
	if o != nil && o.TvQuotaDays.IsSet() {
		return true
	}

	return false
}

// SetTvQuotaDays gets a reference to the given NullableFloat32 and assigns it to the TvQuotaDays field.
func (o *User) SetTvQuotaDays(v float32) {
	o.TvQuotaDays.Set(&v)
}
// SetTvQuotaDaysNil sets the value for TvQuotaDays to be an explicit nil
func (o *User) SetTvQuotaDaysNil() {
	o.TvQuotaDays.Set(nil)
}

// UnsetTvQuotaDays ensures that no value is present for TvQuotaDays, not even an explicit nil
func (o *User) UnsetTvQuotaDays() {
	o.TvQuotaDays.Unset()
}

func (o User) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o User) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["email"] = o.Email
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.PlexUsername) {
		toSerialize["plexUsername"] = o.PlexUsername
	}
	if !IsNil(o.PlexToken) {
		toSerialize["plexToken"] = o.PlexToken
	}
	if !IsNil(o.JellyfinAuthToken) {
		toSerialize["jellyfinAuthToken"] = o.JellyfinAuthToken
	}
	if !IsNil(o.UserType) {
		toSerialize["userType"] = o.UserType
	}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	if !IsNil(o.Avatar) {
		toSerialize["avatar"] = o.Avatar
	}
	toSerialize["createdAt"] = o.CreatedAt
	toSerialize["updatedAt"] = o.UpdatedAt
	if !IsNil(o.Settings) {
		toSerialize["settings"] = o.Settings
	}
	if !IsNil(o.RequestCount) {
		toSerialize["requestCount"] = o.RequestCount
	}
	if !IsNil(o.DisplayName) {
		toSerialize["displayName"] = o.DisplayName
	}
	if o.JellyfinUsername.IsSet() {
		toSerialize["jellyfinUsername"] = o.JellyfinUsername.Get()
	}
	if o.JellyfinUserId.IsSet() {
		toSerialize["jellyfinUserId"] = o.JellyfinUserId.Get()
	}
	if o.PlexId.IsSet() {
		toSerialize["plexId"] = o.PlexId.Get()
	}
	if !IsNil(o.Warnings) {
		toSerialize["warnings"] = o.Warnings
	}
	if o.RecoveryLinkExpirationDate.IsSet() {
		toSerialize["recoveryLinkExpirationDate"] = o.RecoveryLinkExpirationDate.Get()
	}
	if o.AvatarETag.IsSet() {
		toSerialize["avatarETag"] = o.AvatarETag.Get()
	}
	if o.AvatarVersion.IsSet() {
		toSerialize["avatarVersion"] = o.AvatarVersion.Get()
	}
	if o.MovieQuotaLimit.IsSet() {
		toSerialize["movieQuotaLimit"] = o.MovieQuotaLimit.Get()
	}
	if o.MovieQuotaDays.IsSet() {
		toSerialize["movieQuotaDays"] = o.MovieQuotaDays.Get()
	}
	if o.TvQuotaLimit.IsSet() {
		toSerialize["tvQuotaLimit"] = o.TvQuotaLimit.Get()
	}
	if o.TvQuotaDays.IsSet() {
		toSerialize["tvQuotaDays"] = o.TvQuotaDays.Get()
	}
	return toSerialize, nil
}

func (o *User) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"email",
		"createdAt",
		"updatedAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUser := _User{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUser)

	if err != nil {
		return err
	}

	*o = User(varUser)

	return err
}

type NullableUser struct {
	value *User
	isSet bool
}

func (v NullableUser) Get() *User {
	return v.value
}

func (v *NullableUser) Set(val *User) {
	v.value = val
	v.isSet = true
}

func (v NullableUser) IsSet() bool {
	return v.isSet
}

func (v *NullableUser) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUser(val *User) *NullableUser {
	return &NullableUser{value: val, isSet: true}
}

func (v NullableUser) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUser) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


