/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
	"fmt"
)

// checks if the MediaRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MediaRequest{}

// MediaRequest struct for MediaRequest
type MediaRequest struct {
	Id float32 `json:"id"`
	// Status of the request. 1 = PENDING APPROVAL, 2 = APPROVED, 3 = DECLINED
	Status float32 `json:"status"`
	Media *MediaInfo `json:"media,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
	UpdatedAt *string `json:"updatedAt,omitempty"`
	RequestedBy *User `json:"requestedBy,omitempty"`
	ModifiedBy *MediaRequestModifiedBy `json:"modifiedBy,omitempty"`
	Is4k *bool `json:"is4k,omitempty"`
	ServerId *float32 `json:"serverId,omitempty"`
	ProfileId *float32 `json:"profileId,omitempty"`
	RootFolder *string `json:"rootFolder,omitempty"`
	// Type of the request (movie or tv)
	Type *string `json:"type,omitempty"`
	LanguageProfileId NullableFloat32 `json:"languageProfileId,omitempty"`
	Tags []float32 `json:"tags,omitempty"`
	IsAutoRequest *bool `json:"isAutoRequest,omitempty"`
	Seasons []map[string]interface{} `json:"seasons,omitempty"`
	SeasonCount *float32 `json:"seasonCount,omitempty"`
	ProfileName NullableString `json:"profileName,omitempty"`
	CanRemove *bool `json:"canRemove,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _MediaRequest MediaRequest

// NewMediaRequest instantiates a new MediaRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMediaRequest(id float32, status float32) *MediaRequest {
	this := MediaRequest{}
	this.Id = id
	this.Status = status
	return &this
}

// NewMediaRequestWithDefaults instantiates a new MediaRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMediaRequestWithDefaults() *MediaRequest {
	this := MediaRequest{}
	return &this
}

// GetId returns the Id field value
func (o *MediaRequest) GetId() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *MediaRequest) GetIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *MediaRequest) SetId(v float32) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *MediaRequest) GetStatus() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *MediaRequest) GetStatusOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *MediaRequest) SetStatus(v float32) {
	o.Status = v
}

// GetMedia returns the Media field value if set, zero value otherwise.
func (o *MediaRequest) GetMedia() MediaInfo {
	if o == nil || IsNil(o.Media) {
		var ret MediaInfo
		return ret
	}
	return *o.Media
}

// GetMediaOk returns a tuple with the Media field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MediaRequest) GetMediaOk() (*MediaInfo, bool) {
	if o == nil || IsNil(o.Media) {
		return nil, false
	}
	return o.Media, true
}

// HasMedia returns a boolean if a field has been set.
func (o *MediaRequest) HasMedia() bool {
	if o != nil && !IsNil(o.Media) {
		return true
	}

	return false
}

// SetMedia gets a reference to the given MediaInfo and assigns it to the Media field.
func (o *MediaRequest) SetMedia(v MediaInfo) {
	o.Media = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *MediaRequest) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MediaRequest) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *MediaRequest) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *MediaRequest) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *MediaRequest) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MediaRequest) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *MediaRequest) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *MediaRequest) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetRequestedBy returns the RequestedBy field value if set, zero value otherwise.
func (o *MediaRequest) GetRequestedBy() User {
	if o == nil || IsNil(o.RequestedBy) {
		var ret User
		return ret
	}
	return *o.RequestedBy
}

// GetRequestedByOk returns a tuple with the RequestedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MediaRequest) GetRequestedByOk() (*User, bool) {
	if o == nil || IsNil(o.RequestedBy) {
		return nil, false
	}
	return o.RequestedBy, true
}

// HasRequestedBy returns a boolean if a field has been set.
func (o *MediaRequest) HasRequestedBy() bool {
	if o != nil && !IsNil(o.RequestedBy) {
		return true
	}

	return false
}

// SetRequestedBy gets a reference to the given User and assigns it to the RequestedBy field.
func (o *MediaRequest) SetRequestedBy(v User) {
	o.RequestedBy = &v
}

// GetModifiedBy returns the ModifiedBy field value if set, zero value otherwise.
func (o *MediaRequest) GetModifiedBy() MediaRequestModifiedBy {
	if o == nil || IsNil(o.ModifiedBy) {
		var ret MediaRequestModifiedBy
		return ret
	}
	return *o.ModifiedBy
}

// GetModifiedByOk returns a tuple with the ModifiedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MediaRequest) GetModifiedByOk() (*MediaRequestModifiedBy, bool) {
	if o == nil || IsNil(o.ModifiedBy) {
		return nil, false
	}
	return o.ModifiedBy, true
}

// HasModifiedBy returns a boolean if a field has been set.
func (o *MediaRequest) HasModifiedBy() bool {
	if o != nil && !IsNil(o.ModifiedBy) {
		return true
	}

	return false
}

// SetModifiedBy gets a reference to the given MediaRequestModifiedBy and assigns it to the ModifiedBy field.
func (o *MediaRequest) SetModifiedBy(v MediaRequestModifiedBy) {
	o.ModifiedBy = &v
}

// GetIs4k returns the Is4k field value if set, zero value otherwise.
func (o *MediaRequest) GetIs4k() bool {
	if o == nil || IsNil(o.Is4k) {
		var ret bool
		return ret
	}
	return *o.Is4k
}

// GetIs4kOk returns a tuple with the Is4k field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MediaRequest) GetIs4kOk() (*bool, bool) {
	if o == nil || IsNil(o.Is4k) {
		return nil, false
	}
	return o.Is4k, true
}

// HasIs4k returns a boolean if a field has been set.
func (o *MediaRequest) HasIs4k() bool {
	if o != nil && !IsNil(o.Is4k) {
		return true
	}

	return false
}

// SetIs4k gets a reference to the given bool and assigns it to the Is4k field.
func (o *MediaRequest) SetIs4k(v bool) {
	o.Is4k = &v
}

// GetServerId returns the ServerId field value if set, zero value otherwise.
func (o *MediaRequest) GetServerId() float32 {
	if o == nil || IsNil(o.ServerId) {
		var ret float32
		return ret
	}
	return *o.ServerId
}

// GetServerIdOk returns a tuple with the ServerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MediaRequest) GetServerIdOk() (*float32, bool) {
	if o == nil || IsNil(o.ServerId) {
		return nil, false
	}
	return o.ServerId, true
}

// HasServerId returns a boolean if a field has been set.
func (o *MediaRequest) HasServerId() bool {
	if o != nil && !IsNil(o.ServerId) {
		return true
	}

	return false
}

// SetServerId gets a reference to the given float32 and assigns it to the ServerId field.
func (o *MediaRequest) SetServerId(v float32) {
	o.ServerId = &v
}

// GetProfileId returns the ProfileId field value if set, zero value otherwise.
func (o *MediaRequest) GetProfileId() float32 {
	if o == nil || IsNil(o.ProfileId) {
		var ret float32
		return ret
	}
	return *o.ProfileId
}

// GetProfileIdOk returns a tuple with the ProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MediaRequest) GetProfileIdOk() (*float32, bool) {
	if o == nil || IsNil(o.ProfileId) {
		return nil, false
	}
	return o.ProfileId, true
}

// HasProfileId returns a boolean if a field has been set.
func (o *MediaRequest) HasProfileId() bool {
	if o != nil && !IsNil(o.ProfileId) {
		return true
	}

	return false
}

// SetProfileId gets a reference to the given float32 and assigns it to the ProfileId field.
func (o *MediaRequest) SetProfileId(v float32) {
	o.ProfileId = &v
}

// GetRootFolder returns the RootFolder field value if set, zero value otherwise.
func (o *MediaRequest) GetRootFolder() string {
	if o == nil || IsNil(o.RootFolder) {
		var ret string
		return ret
	}
	return *o.RootFolder
}

// GetRootFolderOk returns a tuple with the RootFolder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MediaRequest) GetRootFolderOk() (*string, bool) {
	if o == nil || IsNil(o.RootFolder) {
		return nil, false
	}
	return o.RootFolder, true
}

// HasRootFolder returns a boolean if a field has been set.
func (o *MediaRequest) HasRootFolder() bool {
	if o != nil && !IsNil(o.RootFolder) {
		return true
	}

	return false
}

// SetRootFolder gets a reference to the given string and assigns it to the RootFolder field.
func (o *MediaRequest) SetRootFolder(v string) {
	o.RootFolder = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *MediaRequest) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MediaRequest) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *MediaRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *MediaRequest) SetType(v string) {
	o.Type = &v
}

// GetLanguageProfileId returns the LanguageProfileId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MediaRequest) GetLanguageProfileId() float32 {
	if o == nil || IsNil(o.LanguageProfileId.Get()) {
		var ret float32
		return ret
	}
	return *o.LanguageProfileId.Get()
}

// GetLanguageProfileIdOk returns a tuple with the LanguageProfileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MediaRequest) GetLanguageProfileIdOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.LanguageProfileId.Get(), o.LanguageProfileId.IsSet()
}

// HasLanguageProfileId returns a boolean if a field has been set.
func (o *MediaRequest) HasLanguageProfileId() bool {
	if o != nil && o.LanguageProfileId.IsSet() {
		return true
	}

	return false
}

// SetLanguageProfileId gets a reference to the given NullableFloat32 and assigns it to the LanguageProfileId field.
func (o *MediaRequest) SetLanguageProfileId(v float32) {
	o.LanguageProfileId.Set(&v)
}
// SetLanguageProfileIdNil sets the value for LanguageProfileId to be an explicit nil
func (o *MediaRequest) SetLanguageProfileIdNil() {
	o.LanguageProfileId.Set(nil)
}

// UnsetLanguageProfileId ensures that no value is present for LanguageProfileId, not even an explicit nil
func (o *MediaRequest) UnsetLanguageProfileId() {
	o.LanguageProfileId.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *MediaRequest) GetTags() []float32 {
	if o == nil || IsNil(o.Tags) {
		var ret []float32
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MediaRequest) GetTagsOk() ([]float32, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *MediaRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []float32 and assigns it to the Tags field.
func (o *MediaRequest) SetTags(v []float32) {
	o.Tags = v
}

// GetIsAutoRequest returns the IsAutoRequest field value if set, zero value otherwise.
func (o *MediaRequest) GetIsAutoRequest() bool {
	if o == nil || IsNil(o.IsAutoRequest) {
		var ret bool
		return ret
	}
	return *o.IsAutoRequest
}

// GetIsAutoRequestOk returns a tuple with the IsAutoRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MediaRequest) GetIsAutoRequestOk() (*bool, bool) {
	if o == nil || IsNil(o.IsAutoRequest) {
		return nil, false
	}
	return o.IsAutoRequest, true
}

// HasIsAutoRequest returns a boolean if a field has been set.
func (o *MediaRequest) HasIsAutoRequest() bool {
	if o != nil && !IsNil(o.IsAutoRequest) {
		return true
	}

	return false
}

// SetIsAutoRequest gets a reference to the given bool and assigns it to the IsAutoRequest field.
func (o *MediaRequest) SetIsAutoRequest(v bool) {
	o.IsAutoRequest = &v
}

// GetSeasons returns the Seasons field value if set, zero value otherwise.
func (o *MediaRequest) GetSeasons() []map[string]interface{} {
	if o == nil || IsNil(o.Seasons) {
		var ret []map[string]interface{}
		return ret
	}
	return o.Seasons
}

// GetSeasonsOk returns a tuple with the Seasons field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MediaRequest) GetSeasonsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.Seasons) {
		return nil, false
	}
	return o.Seasons, true
}

// HasSeasons returns a boolean if a field has been set.
func (o *MediaRequest) HasSeasons() bool {
	if o != nil && !IsNil(o.Seasons) {
		return true
	}

	return false
}

// SetSeasons gets a reference to the given []map[string]interface{} and assigns it to the Seasons field.
func (o *MediaRequest) SetSeasons(v []map[string]interface{}) {
	o.Seasons = v
}

// GetSeasonCount returns the SeasonCount field value if set, zero value otherwise.
func (o *MediaRequest) GetSeasonCount() float32 {
	if o == nil || IsNil(o.SeasonCount) {
		var ret float32
		return ret
	}
	return *o.SeasonCount
}

// GetSeasonCountOk returns a tuple with the SeasonCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MediaRequest) GetSeasonCountOk() (*float32, bool) {
	if o == nil || IsNil(o.SeasonCount) {
		return nil, false
	}
	return o.SeasonCount, true
}

// HasSeasonCount returns a boolean if a field has been set.
func (o *MediaRequest) HasSeasonCount() bool {
	if o != nil && !IsNil(o.SeasonCount) {
		return true
	}

	return false
}

// SetSeasonCount gets a reference to the given float32 and assigns it to the SeasonCount field.
func (o *MediaRequest) SetSeasonCount(v float32) {
	o.SeasonCount = &v
}

// GetProfileName returns the ProfileName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *MediaRequest) GetProfileName() string {
	if o == nil || IsNil(o.ProfileName.Get()) {
		var ret string
		return ret
	}
	return *o.ProfileName.Get()
}

// GetProfileNameOk returns a tuple with the ProfileName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *MediaRequest) GetProfileNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProfileName.Get(), o.ProfileName.IsSet()
}

// HasProfileName returns a boolean if a field has been set.
func (o *MediaRequest) HasProfileName() bool {
	if o != nil && o.ProfileName.IsSet() {
		return true
	}

	return false
}

// SetProfileName gets a reference to the given NullableString and assigns it to the ProfileName field.
func (o *MediaRequest) SetProfileName(v string) {
	o.ProfileName.Set(&v)
}
// SetProfileNameNil sets the value for ProfileName to be an explicit nil
func (o *MediaRequest) SetProfileNameNil() {
	o.ProfileName.Set(nil)
}

// UnsetProfileName ensures that no value is present for ProfileName, not even an explicit nil
func (o *MediaRequest) UnsetProfileName() {
	o.ProfileName.Unset()
}

// GetCanRemove returns the CanRemove field value if set, zero value otherwise.
func (o *MediaRequest) GetCanRemove() bool {
	if o == nil || IsNil(o.CanRemove) {
		var ret bool
		return ret
	}
	return *o.CanRemove
}

// GetCanRemoveOk returns a tuple with the CanRemove field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MediaRequest) GetCanRemoveOk() (*bool, bool) {
	if o == nil || IsNil(o.CanRemove) {
		return nil, false
	}
	return o.CanRemove, true
}

// HasCanRemove returns a boolean if a field has been set.
func (o *MediaRequest) HasCanRemove() bool {
	if o != nil && !IsNil(o.CanRemove) {
		return true
	}

	return false
}

// SetCanRemove gets a reference to the given bool and assigns it to the CanRemove field.
func (o *MediaRequest) SetCanRemove(v bool) {
	o.CanRemove = &v
}

func (o MediaRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MediaRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	if !IsNil(o.Media) {
		toSerialize["media"] = o.Media
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if !IsNil(o.RequestedBy) {
		toSerialize["requestedBy"] = o.RequestedBy
	}
	if !IsNil(o.ModifiedBy) {
		toSerialize["modifiedBy"] = o.ModifiedBy
	}
	if !IsNil(o.Is4k) {
		toSerialize["is4k"] = o.Is4k
	}
	if !IsNil(o.ServerId) {
		toSerialize["serverId"] = o.ServerId
	}
	if !IsNil(o.ProfileId) {
		toSerialize["profileId"] = o.ProfileId
	}
	if !IsNil(o.RootFolder) {
		toSerialize["rootFolder"] = o.RootFolder
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if o.LanguageProfileId.IsSet() {
		toSerialize["languageProfileId"] = o.LanguageProfileId.Get()
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.IsAutoRequest) {
		toSerialize["isAutoRequest"] = o.IsAutoRequest
	}
	if !IsNil(o.Seasons) {
		toSerialize["seasons"] = o.Seasons
	}
	if !IsNil(o.SeasonCount) {
		toSerialize["seasonCount"] = o.SeasonCount
	}
	if o.ProfileName.IsSet() {
		toSerialize["profileName"] = o.ProfileName.Get()
	}
	if !IsNil(o.CanRemove) {
		toSerialize["canRemove"] = o.CanRemove
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MediaRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMediaRequest := _MediaRequest{}

	err = json.Unmarshal(data, &varMediaRequest)

	if err != nil {
		return err
	}

	*o = MediaRequest(varMediaRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "status")
		delete(additionalProperties, "media")
		delete(additionalProperties, "createdAt")
		delete(additionalProperties, "updatedAt")
		delete(additionalProperties, "requestedBy")
		delete(additionalProperties, "modifiedBy")
		delete(additionalProperties, "is4k")
		delete(additionalProperties, "serverId")
		delete(additionalProperties, "profileId")
		delete(additionalProperties, "rootFolder")
		delete(additionalProperties, "type")
		delete(additionalProperties, "languageProfileId")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "isAutoRequest")
		delete(additionalProperties, "seasons")
		delete(additionalProperties, "seasonCount")
		delete(additionalProperties, "profileName")
		delete(additionalProperties, "canRemove")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMediaRequest struct {
	value *MediaRequest
	isSet bool
}

func (v NullableMediaRequest) Get() *MediaRequest {
	return v.value
}

func (v *NullableMediaRequest) Set(val *MediaRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableMediaRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableMediaRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMediaRequest(val *MediaRequest) *NullableMediaRequest {
	return &NullableMediaRequest{value: val, isSet: true}
}

func (v NullableMediaRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMediaRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


