/*
Seerr API

This is the documentation for the Seerr API backend.  Two primary authentication methods are supported:  - **Cookie Authentication**: A valid sign-in to the `/auth/plex` or `/auth/local` will generate a valid authentication cookie. - **API Key Authentication**: Sign-in is also possible by passing an `X-Api-Key` header along with a valid API Key generated by Seerr. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package api

import (
	"encoding/json"
)

// checks if the WatchProviders type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WatchProviders{}

// WatchProviders struct for WatchProviders
type WatchProviders struct {
	Iso31661 *string `json:"iso_3166_1,omitempty"`
	Link *string `json:"link,omitempty"`
	Buy []WatchProviderDetails `json:"buy,omitempty"`
	Flatrate []WatchProviderDetails `json:"flatrate,omitempty"`
}

// NewWatchProviders instantiates a new WatchProviders object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWatchProviders() *WatchProviders {
	this := WatchProviders{}
	return &this
}

// NewWatchProvidersWithDefaults instantiates a new WatchProviders object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWatchProvidersWithDefaults() *WatchProviders {
	this := WatchProviders{}
	return &this
}

// GetIso31661 returns the Iso31661 field value if set, zero value otherwise.
func (o *WatchProviders) GetIso31661() string {
	if o == nil || IsNil(o.Iso31661) {
		var ret string
		return ret
	}
	return *o.Iso31661
}

// GetIso31661Ok returns a tuple with the Iso31661 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchProviders) GetIso31661Ok() (*string, bool) {
	if o == nil || IsNil(o.Iso31661) {
		return nil, false
	}
	return o.Iso31661, true
}

// HasIso31661 returns a boolean if a field has been set.
func (o *WatchProviders) HasIso31661() bool {
	if o != nil && !IsNil(o.Iso31661) {
		return true
	}

	return false
}

// SetIso31661 gets a reference to the given string and assigns it to the Iso31661 field.
func (o *WatchProviders) SetIso31661(v string) {
	o.Iso31661 = &v
}

// GetLink returns the Link field value if set, zero value otherwise.
func (o *WatchProviders) GetLink() string {
	if o == nil || IsNil(o.Link) {
		var ret string
		return ret
	}
	return *o.Link
}

// GetLinkOk returns a tuple with the Link field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchProviders) GetLinkOk() (*string, bool) {
	if o == nil || IsNil(o.Link) {
		return nil, false
	}
	return o.Link, true
}

// HasLink returns a boolean if a field has been set.
func (o *WatchProviders) HasLink() bool {
	if o != nil && !IsNil(o.Link) {
		return true
	}

	return false
}

// SetLink gets a reference to the given string and assigns it to the Link field.
func (o *WatchProviders) SetLink(v string) {
	o.Link = &v
}

// GetBuy returns the Buy field value if set, zero value otherwise.
func (o *WatchProviders) GetBuy() []WatchProviderDetails {
	if o == nil || IsNil(o.Buy) {
		var ret []WatchProviderDetails
		return ret
	}
	return o.Buy
}

// GetBuyOk returns a tuple with the Buy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchProviders) GetBuyOk() ([]WatchProviderDetails, bool) {
	if o == nil || IsNil(o.Buy) {
		return nil, false
	}
	return o.Buy, true
}

// HasBuy returns a boolean if a field has been set.
func (o *WatchProviders) HasBuy() bool {
	if o != nil && !IsNil(o.Buy) {
		return true
	}

	return false
}

// SetBuy gets a reference to the given []WatchProviderDetails and assigns it to the Buy field.
func (o *WatchProviders) SetBuy(v []WatchProviderDetails) {
	o.Buy = v
}

// GetFlatrate returns the Flatrate field value if set, zero value otherwise.
func (o *WatchProviders) GetFlatrate() []WatchProviderDetails {
	if o == nil || IsNil(o.Flatrate) {
		var ret []WatchProviderDetails
		return ret
	}
	return o.Flatrate
}

// GetFlatrateOk returns a tuple with the Flatrate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WatchProviders) GetFlatrateOk() ([]WatchProviderDetails, bool) {
	if o == nil || IsNil(o.Flatrate) {
		return nil, false
	}
	return o.Flatrate, true
}

// HasFlatrate returns a boolean if a field has been set.
func (o *WatchProviders) HasFlatrate() bool {
	if o != nil && !IsNil(o.Flatrate) {
		return true
	}

	return false
}

// SetFlatrate gets a reference to the given []WatchProviderDetails and assigns it to the Flatrate field.
func (o *WatchProviders) SetFlatrate(v []WatchProviderDetails) {
	o.Flatrate = v
}

func (o WatchProviders) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WatchProviders) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Iso31661) {
		toSerialize["iso_3166_1"] = o.Iso31661
	}
	if !IsNil(o.Link) {
		toSerialize["link"] = o.Link
	}
	if !IsNil(o.Buy) {
		toSerialize["buy"] = o.Buy
	}
	if !IsNil(o.Flatrate) {
		toSerialize["flatrate"] = o.Flatrate
	}
	return toSerialize, nil
}

type NullableWatchProviders struct {
	value *WatchProviders
	isSet bool
}

func (v NullableWatchProviders) Get() *WatchProviders {
	return v.value
}

func (v *NullableWatchProviders) Set(val *WatchProviders) {
	v.value = val
	v.isSet = true
}

func (v NullableWatchProviders) IsSet() bool {
	return v.isSet
}

func (v *NullableWatchProviders) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWatchProviders(val *WatchProviders) *NullableWatchProviders {
	return &NullableWatchProviders{value: val, isSet: true}
}

func (v NullableWatchProviders) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWatchProviders) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


