/*
Seerr API

Testing BlocklistAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api

import (
	"context"
	openapiclient "seerr-cli/pkg/api"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_api_BlocklistAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BlocklistAPIService BlacklistGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.BlocklistAPI.BlacklistGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BlocklistAPIService BlacklistPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.BlocklistAPI.BlacklistPost(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BlocklistAPIService BlacklistTmdbIdDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var tmdbId string

		httpRes, err := apiClient.BlocklistAPI.BlacklistTmdbIdDelete(context.Background(), tmdbId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BlocklistAPIService BlacklistTmdbIdGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var tmdbId string

		httpRes, err := apiClient.BlocklistAPI.BlacklistTmdbIdGet(context.Background(), tmdbId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BlocklistAPIService BlocklistGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.BlocklistAPI.BlocklistGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BlocklistAPIService BlocklistPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.BlocklistAPI.BlocklistPost(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BlocklistAPIService BlocklistTmdbIdDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var tmdbId string

		httpRes, err := apiClient.BlocklistAPI.BlocklistTmdbIdDelete(context.Background(), tmdbId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BlocklistAPIService BlocklistTmdbIdGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var tmdbId string

		httpRes, err := apiClient.BlocklistAPI.BlocklistTmdbIdGet(context.Background(), tmdbId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
