/*
Seerr API

Testing OverrideruleAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	openapiclient "seer-cli/pkg/api"
	"testing"
)

func Test_api_OverrideruleAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OverrideruleAPIService OverrideRuleGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.OverrideruleAPI.OverrideRuleGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OverrideruleAPIService OverrideRulePost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.OverrideruleAPI.OverrideRulePost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OverrideruleAPIService OverrideRuleRuleIdDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var ruleId float32

		resp, httpRes, err := apiClient.OverrideruleAPI.OverrideRuleRuleIdDelete(context.Background(), ruleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OverrideruleAPIService OverrideRuleRuleIdPut", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var ruleId float32

		resp, httpRes, err := apiClient.OverrideruleAPI.OverrideRuleRuleIdPut(context.Background(), ruleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
