/*
Seerr API

Testing PersonAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api

import (
	"context"
	openapiclient "seerr-cli/pkg/api"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_api_PersonAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test PersonAPIService PersonPersonIdCombinedCreditsGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var personId float32

		resp, httpRes, err := apiClient.PersonAPI.PersonPersonIdCombinedCreditsGet(context.Background(), personId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test PersonAPIService PersonPersonIdGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var personId float32

		resp, httpRes, err := apiClient.PersonAPI.PersonPersonIdGet(context.Background(), personId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
