/*
Seerr API

Testing WatchlistAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	openapiclient "seer-cli/pkg/api"
	"testing"
)

func Test_api_WatchlistAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test WatchlistAPIService UserUserIdWatchlistGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var userId float32

		resp, httpRes, err := apiClient.WatchlistAPI.UserUserIdWatchlistGet(context.Background(), userId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WatchlistAPIService WatchlistPost", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.WatchlistAPI.WatchlistPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test WatchlistAPIService WatchlistTmdbIdDelete", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var tmdbId string

		httpRes, err := apiClient.WatchlistAPI.WatchlistTmdbIdDelete(context.Background(), tmdbId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
