/*
Seerr API

Testing CollectionAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package api

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	openapiclient "seer-cli/pkg/api"
	"testing"
)

func Test_api_CollectionAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test CollectionAPIService CollectionCollectionIdGet", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var collectionId float32

		resp, httpRes, err := apiClient.CollectionAPI.CollectionCollectionIdGet(context.Background(), collectionId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
